### ISSUE TITLE
Adding a key value that need a dictionary or an array?

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/AppBundler-DMS#1]
How to add a key value like the following?
```
<key>LSEnvironment</key>
<dict>
        <key>MYKEY</key>
        <string>/etc/share/blablabla.paf</string>
</dict>
```

**Comment by Sami32** [comment]
```
<plistentry key="LSEnvironment"/>
<plistentry dict/>
<plistentry key="MYKEY" value="/etc/share/blablabla.paf" type="string"/>
<plistentry dict/>
```
Do that will work?

**Comment by Nadahar** [comment]
> How to add a key value like the following?

I have no idea, I haven't looked at the AppBundler for a long time.

> Do that will work?

I doubt it.

Before I start digging into how to do this, I'd like to be sure that we really need this. What do with need a dictionary entry for?

**Comment by Sami32** [comment]
For that for example:
```
 <key>LSEnvironment</key>
 <dict>
     <key>MinimumSystemVersion</key>
     <string>10.6.0</string>
 </dict>
```
As using the following doesn't work well on all plateforms:
https://www.bignerdranch.com/blog/requiring-a-minimum-version-of-os-x-for-your-application/
```
<key>LSMinimumSystemVersion</key>
<string>10.6.0</string>
```

**Comment by Sami32** [comment]
But as i want also use it for an other key with similar structure it shouldn't be hardcoded if possible.

**Comment by Nadahar** [comment]
Have you tried the "logical way"? By that i mean something like:
```xml
<plistentry key="LSEnvironment" type="dict">
    <plistentry key="MYKEY" value="/etc/share/blablabla.paf" type="string"/>
</plistentry>
```

**Comment by Sami32** [comment]
Logical? me, Lol
Of course not ;P

**Comment by Sami32** [comment]
>Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (Prepare-files-PKG) on project dms: An Ant BuildException has occured: plistentry doesn't support the nested "plistentry" element.

**Comment by Nadahar** [comment]
It seems that you can set `minimumSystemVersion` directly. I assume that means that you can do:
```xml
<bundleapp outputdirectory="${project.build.directory}/${project.build.finalName}-distribution"
				           name="${project.name}"
				           displayname="${project.name}"
				           executableName="DMS"
				           identifier="net.pms.PMS"
				           shortversion="${project.version.short}"
				           version="${project.version}"
				           icon="${project.basedir}/src/main/resources/images/logo.icns"
				           applicationCategory="public.app-category.entertainment"
				           workingdirectory="$APP_ROOT/Contents/Resources"
				           mainclassname="net.pms.PMS"
				           minimumSystemVersion="10.6.0">
					<classpath file="${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar"/>
					<option value="-Xmx768M"/>
					<option value="-Xss16M"/>
					<option value="-Dfile.encoding=UTF-8"/>
					<option value="-Djava.net.preferIPv4Stack=true"/>
					<option value="-Xdock:name=Digital Media Server"/>
</bundleapp>
```

**Comment by Nadahar** [comment]
You can see what settings that are predefined here: https://github.com/DigitalMediaServer/AppBundler/blob/a7462509c1efa81085e4153d77483b72d0d482bf/appbundler/src/com/oracle/appbundler/AppBundlerTask.java#L68-L109

As you see, you should also be able to define additional "environment" entries by using `<environments>..</environments>`

**Comment by Nadahar** [comment]
The above might also work by doing something like:
```xml
<plistentry key="LSEnvironment" type="dict">
    <MYKEY>/etc/share/blablabla.paf</MYKEY>
</plistentry>
```

**Comment by Sami32** [comment]
Yes, i know it was only an example, as i already use that `minimumSystemVersion` setting but i didn't want post the one i need ;)
Who wrote that documentation ;P
Ok, lets try that then :)

**Comment by Nadahar** [comment]
That's why I asked you what you needed it for.

About the formatting of the XML, I have no idea what works, since this is Ant. I thought you knew everything about Ant by now :wink:

**Comment by Sami32** [comment]
The use of `plistentry` didn't worked, same error message.
And i have no idea how to use `environments`

**Comment by Nadahar** [comment]
Until you tell me what options you want to add, I can't help you. I just see that ```environments``` are defined in the source, so I assume that you can just define it using "standard Ant rules" - whatever those are.

**Comment by Sami32** [comment]
It is not coming from Ant but from that using `plistentry` that way is not possible IMO.

**Comment by Nadahar** [comment]
The error is coming from Ant. There is no such error message in AppBundler. Ant has to "translate" the specified options to Java arguments, and I'm pretty sure that it's this code that gives the error. That said, I don't think you can use dictionaries with `plistentry`, but you should be able to add it to `environments` as long as what you wish to add should be listed as such.

**Comment by Sami32** [comment]
`<key>LSMinimumSystemVersion</key>
<string>10.6.0</string>` is what is set by the code when using .`minimumSystemVersion`.
`plistentry` is only able to handle, add simple `<key>` `<string>` pair entries.
`environments` only handle `name` and `value` fields so also if i end to make it work i don't think that it  should be able to add entries with dictionary as i want IMO.

**Comment by Sami32** [comment]
That could explain why you have hardcoded this:
```
<key>LSEnvironment</key>
<dict>
<key>LC_CTYPE</key>
<string>UTF-8</string>
</dict>
```

**Comment by Nadahar** [comment]
*I* didn't hardcode that, it's from the upstream repo. I would expect that "name" is mapped to "key" and "value" is mapped to "string", but there's only one way to know for sure. Again, as long as you won't share what you're trying to do, there's nothing more I can do.

**Comment by Sami32** [comment]
Please, if you are able to make this plugin doing that:
```
<key>LSEnvironment</key>
 <dict>
     <key>MinimumSystemVersion</key>
     <string>10.6.0</string>
 </dict>
```
feel free to share ;)

**Comment by Nadahar** [comment]
```xml
<environment name="MinimumSystemVersion" value="10.5.0"/>
```

**Comment by Sami32** [comment]
```
<?xml version="1.0" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDevelopmentRegion</key>
<string>English</string>
<key>CFBundleExecutable</key>
<string>DMS</string>
<key>CFBundleIconFile</key>
<string>logo.icns</string>
<key>CFBundleIdentifier</key>
<string>net.pms.PMS</string>
<key>CFBundleDisplayName</key>
<string>Digital Media Server</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundleName</key>
<string>Digital Media Server</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleShortVersionString</key>
<string>1.0</string>
<key>CFBundleVersion</key>
<string>0.3.0</string>
<key>CFBundleSignature</key>
<string>DMS </string>
<key>NSHumanReadableCopyright</key>
<string>Copyleft (?) 2018 Digital Media Server.</string>
<key>LSMinimumSystemVersion</key>
<string>10.6.0</string>
<key>LSApplicationCategoryType</key>
<string>public.app-category.entertainment</string>
<key>NSHighResolutionCapable</key>
<true/>
<key>NSSupportsAutomaticGraphicsSwitching</key>
<true/>
<key>JVMVersion</key>
<string>1.7+</string>
<key>WorkingDirectory</key>
<string>$APP_ROOT/Contents/Resources</string>
<key>JVMMainClassName</key>
<string>net.pms.PMS</string>
<key>CFBundleDocumentTypes</key>
<array>
</array>
<key>LSArchitecturePriority</key>
<array>
<string>x86_64</string>
</array>
<key>LSEnvironment</key>
<dict>
<key>LC_CTYPE</key>
<string>UTF-8</string>
</dict>
<key>JVMOptions</key>
<array>
<string>-Dfile.encoding=UTF-8</string>
<string>-Djava.net.preferIPv4Stack=true</string>
<string>-Xdock:icon=Contents/Resources/logo.icns</string>
<string>-Xdock:name=Digital Media Server</string>
<string>-Djna.nosys=true</string>
</array>
<key>JVMDefaultOptions</key>
<dict>
</dict>
<key>JVMArguments</key>
<array>
</array>
</plist>
```
And what is wished to be obtained: (but by now only manual editing is possible AFAIK)
```
<?xml version="1.0" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDevelopmentRegion</key>
<string>English</string>
<key>CFBundleExecutable</key>
<string>DMS</string>
<key>CFBundleIconFile</key>
<string>logo.icns</string>
<key>CFBundleIdentifier</key>
<string>net.pms.PMS</string>
<key>CFBundleDisplayName</key>
<string>Digital Media Server</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundleName</key>
<string>Digital Media Server</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleShortVersionString</key>
<string>1.0</string>
<key>CFBundleVersion</key>
<string>0.3.0</string>
<key>CFBundleSignature</key>
<string>DMS </string>
<key>NSHumanReadableCopyright</key>
<string>Copyleft (?) 2018 Digital Media Server.</string>
<key>LSApplicationCategoryType</key>
<string>public.app-category.entertainment</string>
<key>NSHighResolutionCapable</key>
<true/>
<key>NSSupportsAutomaticGraphicsSwitching</key>
<true/>
<key>JVMVersion</key>
<string>1.7+</string>
<key>WorkingDirectory</key>
<string>$APP_ROOT/Contents/Resources</string>
<key>JVMMainClassName</key>
<string>net.pms.PMS</string>
<key>CFBundleDocumentTypes</key>
<array>
</array>
<key>LSArchitecturePriority</key>
<array>
<string>x86_64</string>
</array>
<key>LSEnvironment</key>
<dict>
<key>MinimumSystemVersion</key>
<string>10.6.0</string>
<key>LC_CTYPE</key>
<string>UTF-8</string>
</dict>
<key>JVMOptions</key>
<array>
<string>-Dfile.encoding=UTF-8</string>
<string>-Djava.net.preferIPv4Stack=true</string>
<string>-Xdock:icon=Contents/Resources/logo.icns</string>
<string>-Xdock:name=Digital Media Server</string>
<string>-Djna.nosys=true</string>
</array>
<key>JVMDefaultOptions</key>
<dict>
</dict>
<key>JVMArguments</key>
<array>
</array>
</dict>
</plist>
```
Old way making is far simpler ;P

**Comment by Sami32** [comment]
This plugin is not able to handle that AFAIK.

**Comment by Nadahar** [comment]
That's strange because it produced this correctly when I just tested on the macOS VM.

**Comment by Sami32** [comment]
Sorry, it is possible but when using `environment` and not `environments`. That is where skill or good documentation can make difference...
https://github.com/DigitalMediaServer/AppBundler/issues/1#issuecomment-427900327

Thanks for your help ;)

**Comment by Sami32** [comment]
I didn't saw that you had posted before my test.
